### PR TITLE
Fix conflict with serverless-pseudo-parameters plugin

### PR DESCRIPTION
**Pull request by laszlominczer**

### CODE REVIEW

**Comment by andrepintorj** [comment]
This is a nice fix since a lot of people seem to use serverless-pseudo-parameters plugin...

**Comment by barendb** [comment]
~Yo @mooyoul any update on this? Would really like to see this being published.~

**Comment by piohhmy** [comment]
Hi @mooyoul I also would love to see this get merged and published!

**Comment by codyfazio** [comment]
@mooyoul Any chance of getting this approved and merged? Would also really like to see this published!

**Comment by barendb** [comment]
PS: I tested this fix using `patch-package` and didn't work for me.

I don't the problem is how the parts of the ARN is extracted, but at what stage of the Serverless lifecycle the plugin runs and wether is using the right "replaced config". Hope that makes sense, I ran out of time trying to figure it out.

**Comment by mooyoul** [comment]
Hello all. I rewrote almost all codes (resolving/replacing layer version related logic) and New version just published to npm!

Please try out new version of serverless-latest-layer-version plugin and please let me know the results :)
Thanks for your patience!

**Comment by barendb** [comment]
Tested and works like a charm! Thanks @mooyoul really appreciate it! ❤️

**Comment by piohhmy** [comment]
Thanks @mooyoul !

**Comment by mooyoul** [comment]
Glad to hear it works 🎉 If this plugin helped you, Don't forget to give a star ;) Thanks!

**Pull request closed without merging**
